#######################
# General Configuration
#######################
dist: xenial
language: cpp

script:
  - ./releng/build_and_test.sh $CROSS

matrix:
  include:
    - os: linux
      name: "Cross Compilation Test"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - gcc-7-multilib
            - g++-7-multilib 
            - linux-libc-dev:i386
            - linux-libc-dev
            - mingw-w64
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CROSS=--cross"
        
    - os: linux
      name: "GCC 4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - g++-4.9
            
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      name: "GCC 5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      name: "GCC 6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      name: "GCC 7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      name: "GCC 8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      name: "Clang 3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - os: linux
      name: "Clang 3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

    - os: linux
      name: "Clang 3.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - os: linux
      name: "Clang 3.9"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      name: "Clang 4.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      name: "Clang 5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - unzip
            - zip
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


before_install:
    - eval "${MATRIX_EVAL}"


notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: change
    on_failure: change
    rooms:
      - vaader-ietr:iLrCNf4jussBcDgnl8EvN2j5#spider

#skip install step before each stage by running the /bin/true command
install: true
